version: "3"

services:
  image-bay-generate:
    container_name: image-bay-generate
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    image: image-bay-generate:latest
    volumes:
      - ./:/app

